### ISSUE TITLE
Example configs are not included in debian packages

### ISSUE THREAD

**Issue by p-blomberg** [dotse/dnscheck#108]
I've built debian packages with the instructions in README.debian. After installing both packages, the directory /etc/dnscheck is empty. 

I expected to find config.yaml and/or policy.yaml, and webui_config.php, in this directory, and expected to just need to edit them with my database access information.

Are there example configs? Where?

**Comment by einar** [comment]
You can find examples here on Github in the respective directories (/webui and /engine/config); cant remember if we did this on purpose or not (excluded the configs) but internally we keep no configurations in packages so it could be that we actually did remove them. Sorry if that was unclear.

When it comes to DNSCheck itself we're focusing almost all our efforts on our new tool Zonemaster now (https://github.com/dotse/zonemaster/tree/master) so support and fixes concerning DNSCheck will not come as often as before and we might even not get the resources to maintain it at all soon. So, if you're a new user, you probably want to consider using Zonemaster instead. :)
