### ISSUE TITLE
New algorithm 13 not recognized (works in Zonemaster though)

### ISSUE THREAD

**Issue by einar** [dotse/dnscheck#113]
Look at "http://dnscheck.iis.se/?time=1451463536&id=5385081&view=basic&test=standard" and "http://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml". Not sure if we are allowed to fix this but let's keep it here for future reference anyhow. :)

**Comment by pawal** [comment]
This is not really a problem with DNSCheck itself, it is Net::DNS that does not seem to have it fully implemented. DNSCheck has code that can use Net::DNS once it has that functionality.

**Comment by pawal** [comment]
This is the same as #112.

**Comment by Stricted** [comment]
it seems that a newer version of net::dns have the Algorithms implemented

**Comment by matsduf** [comment]
@pawal, is this resolved by PR #117?

**Comment by pawal** [comment]
Yes, looks lite it should be fine now.

**Comment by matsduf** [comment]
Resolved by PR #117
